# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sreedevi Krishnan
email: sreedevik29@gmail.com
description: Pondering thoughts and portfolio of Sreedevi Krishnan
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sreedevi.ca" # PROD
# url: "http://localhost:4000" # DEV
# twitter_username: ""
github_username:  sreedevik29
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
